name: circulari_widgetbook
description: Widgetbook for circulari_ui components.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.11.4
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  circulari_ui:
    path: ../circulari_ui
  widgetbook: ^3.0.0

flutter:
  uses-material-design: true
